# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Home.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QSizePolicy, QWidget)
import templates.images
import templates.icones


class Ui_Home(object):
    def setupUi(self, Home):
        if not Home.objectName():
            Home.setObjectName(u"Home")
        Home.resize(850, 506)
        Home.setMaximumSize(QSize(850, 600))
        self.tela_principal_home = QWidget(Home)
        self.tela_principal_home.setObjectName(u"tela_principal_home")
        self.tela_home = QFrame(self.tela_principal_home)
        self.tela_home.setObjectName(u"tela_home")
        self.tela_home.setGeometry(QRect(0, 0, 850, 500))
        self.tela_home.setMaximumSize(QSize(899, 600))
        self.tela_home.setStyleSheet(u"background-color: rgb(18, 18, 18);\n"
"")
        self.tela_home.setFrameShape(QFrame.Shape.StyledPanel)
        self.tela_home.setFrameShadow(QFrame.Shadow.Raised)
        self.menu_inicial = QFrame(self.tela_home)
        self.menu_inicial.setObjectName(u"menu_inicial")
        self.menu_inicial.setGeometry(QRect(0, -1, 851, 51))
        self.menu_inicial.setFrameShape(QFrame.Shape.StyledPanel)
        self.menu_inicial.setFrameShadow(QFrame.Shadow.Raised)
        self.txt_logo = QLabel(self.menu_inicial)
        self.txt_logo.setObjectName(u"txt_logo")
        self.txt_logo.setGeometry(QRect(80, 20, 141, 16))
        self.icon_casa = QLabel(self.menu_inicial)
        self.icon_casa.setObjectName(u"icon_casa")
        self.icon_casa.setGeometry(QRect(330, 20, 21, 16))
        self.icon_casa.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.icon_casa.setPixmap(QPixmap(u":/icones/icons/casa.png"))
        self.icon_casa.setScaledContents(True)
        self.icon_heart = QLabel(self.menu_inicial)
        self.icon_heart.setObjectName(u"icon_heart")
        self.icon_heart.setGeometry(QRect(390, 20, 21, 16))
        self.icon_heart.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.icon_heart.setPixmap(QPixmap(u":/icones/icons/icon_favoritos.png"))
        self.icon_heart.setScaledContents(True)
        self.icon_cash = QLabel(self.menu_inicial)
        self.icon_cash.setObjectName(u"icon_cash")
        self.icon_cash.setGeometry(QRect(450, 20, 31, 21))
        self.icon_cash.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.icon_cash.setPixmap(QPixmap(u":/icones/icons/Cash.png"))
        self.icon_cash.setScaledContents(True)
        self.icon_perfil = QLabel(self.menu_inicial)
        self.icon_perfil.setObjectName(u"icon_perfil")
        self.icon_perfil.setGeometry(QRect(520, 20, 21, 21))
        self.icon_perfil.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.icon_perfil.setPixmap(QPixmap(u":/icones/icons/user.png"))
        self.icon_perfil.setScaledContents(True)
        self.img_carrossel = QLabel(self.tela_home)
        self.img_carrossel.setObjectName(u"img_carrossel")
        self.img_carrossel.setGeometry(QRect(150, 55, 561, 241))
        self.img_carrossel.setStyleSheet(u"background-color: rgb(18, 18, 18);\n"
"")
        self.img_carrossel.setPixmap(QPixmap(u":/images/imagens/img_JohnWick.png"))
        self.img_carrossel.setScaledContents(True)
        self.icon_trespontos = QLabel(self.tela_home)
        self.icon_trespontos.setObjectName(u"icon_trespontos")
        self.icon_trespontos.setGeometry(QRect(400, 230, 51, 61))
        self.icon_trespontos.setStyleSheet(u"background-color: rgba(0, 0, 0, 0);")
        self.txt_acao = QLabel(self.tela_home)
        self.txt_acao.setObjectName(u"txt_acao")
        self.txt_acao.setGeometry(QRect(90, 320, 31, 16))
        self.txt_comedia = QLabel(self.tela_home)
        self.txt_comedia.setObjectName(u"txt_comedia")
        self.txt_comedia.setGeometry(QRect(140, 320, 49, 16))
        self.txt_suspense = QLabel(self.tela_home)
        self.txt_suspense.setObjectName(u"txt_suspense")
        self.txt_suspense.setGeometry(QRect(220, 320, 61, 16))
        self.txt_terror = QLabel(self.tela_home)
        self.txt_terror.setObjectName(u"txt_terror")
        self.txt_terror.setGeometry(QRect(300, 320, 41, 16))
        self.img_ultimato = QLabel(self.tela_home)
        self.img_ultimato.setObjectName(u"img_ultimato")
        self.img_ultimato.setGeometry(QRect(230, 350, 100, 90))
        self.img_ultimato.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.img_ultimato.setPixmap(QPixmap(u":/images/imagens/img_ultimato.png"))
        self.img_ultimato.setScaledContents(True)
        self.img_minions = QLabel(self.tela_home)
        self.img_minions.setObjectName(u"img_minions")
        self.img_minions.setGeometry(QRect(370, 350, 100, 90))
        self.img_minions.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.img_minions.setPixmap(QPixmap(u":/images/imagens/img_meumalvadofav.png"))
        self.img_minions.setScaledContents(True)
        self.img_tel_preto = QLabel(self.tela_home)
        self.img_tel_preto.setObjectName(u"img_tel_preto")
        self.img_tel_preto.setGeometry(QRect(510, 350, 100, 90))
        self.img_tel_preto.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.img_tel_preto.setPixmap(QPixmap(u":/images/imagens/img_tefonepreto.png"))
        self.img_tel_preto.setScaledContents(True)
        self.img_fragmentado = QLabel(self.tela_home)
        self.img_fragmentado.setObjectName(u"img_fragmentado")
        self.img_fragmentado.setGeometry(QRect(650, 350, 100, 90))
        self.img_fragmentado.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.img_fragmentado.setStyleSheet(u"border-radius: 10px;")
        self.img_fragmentado.setPixmap(QPixmap(u":/images/imagens/img_fragmentado.png"))
        self.img_fragmentado.setScaledContents(True)
        self.img_fragmentado.setWordWrap(False)
        self.img_invDoMal = QLabel(self.tela_home)
        self.img_invDoMal.setObjectName(u"img_invDoMal")
        self.img_invDoMal.setGeometry(QRect(90, 350, 100, 91))
        self.img_invDoMal.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.img_invDoMal.setPixmap(QPixmap(u":/images/imagens/img_inv.domal.png"))
        self.img_invDoMal.setScaledContents(True)
        self.txt_invDoMal = QLabel(self.tela_home)
        self.txt_invDoMal.setObjectName(u"txt_invDoMal")
        self.txt_invDoMal.setGeometry(QRect(100, 450, 91, 16))
        self.txt_ultimato = QLabel(self.tela_home)
        self.txt_ultimato.setObjectName(u"txt_ultimato")
        self.txt_ultimato.setGeometry(QRect(230, 450, 101, 16))
        self.txt_minios = QLabel(self.tela_home)
        self.txt_minios.setObjectName(u"txt_minios")
        self.txt_minios.setGeometry(QRect(390, 450, 61, 16))
        self.txt_tel_preto = QLabel(self.tela_home)
        self.txt_tel_preto.setObjectName(u"txt_tel_preto")
        self.txt_tel_preto.setGeometry(QRect(520, 450, 81, 16))
        self.txt_fragmentado = QLabel(self.tela_home)
        self.txt_fragmentado.setObjectName(u"txt_fragmentado")
        self.txt_fragmentado.setGeometry(QRect(660, 450, 71, 16))
        Home.setCentralWidget(self.tela_principal_home)

        self.retranslateUi(Home)

        QMetaObject.connectSlotsByName(Home)
    # setupUi

    def retranslateUi(self, Home):
        Home.setWindowTitle(QCoreApplication.translate("Home", u"MainWindow", None))
        self.txt_logo.setText(QCoreApplication.translate("Home", u"<html><head/><body><p>Bem Vindo <span style=\" font-weight:700; color:#c5444c;\">ProbreVision</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.icon_casa.setToolTip(QCoreApplication.translate("Home", u"Home", None))
#endif // QT_CONFIG(tooltip)
        self.icon_casa.setText("")
#if QT_CONFIG(tooltip)
        self.icon_heart.setToolTip(QCoreApplication.translate("Home", u"Favoritos", None))
#endif // QT_CONFIG(tooltip)
        self.icon_heart.setText("")
#if QT_CONFIG(tooltip)
        self.icon_cash.setToolTip(QCoreApplication.translate("Home", u"Bilhetes", None))
#endif // QT_CONFIG(tooltip)
        self.icon_cash.setText("")
#if QT_CONFIG(tooltip)
        self.icon_perfil.setToolTip(QCoreApplication.translate("Home", u"Perfil", None))
#endif // QT_CONFIG(tooltip)
        self.icon_perfil.setText("")
        self.img_carrossel.setText("")
        self.icon_trespontos.setText(QCoreApplication.translate("Home", u"<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:700; color:#c5444c;\">.</span><span style=\" font-size:36pt; font-weight:700;\">..</span></p></body></html>", None))
        self.txt_acao.setText(QCoreApplication.translate("Home", u"<html><head/><body><p><span style=\" font-weight:700; text-decoration: underline; color:#c5444c;\">A\u00e7\u00e3</span><span style=\" font-weight:700; color:#c5444c;\">o</span></p></body></html>", None))
        self.txt_comedia.setText(QCoreApplication.translate("Home", u"<html><head/><body><p><span style=\" font-weight:700; color:#ffffff;\">Com\u00e9dia</span></p></body></html>", None))
        self.txt_suspense.setText(QCoreApplication.translate("Home", u"<html><head/><body><p><span style=\" font-weight:700; color:#ffffff;\">Suspense</span></p></body></html>", None))
        self.txt_terror.setText(QCoreApplication.translate("Home", u"<html><head/><body><p><span style=\" font-weight:700; color:#ffffff;\">Terror</span></p></body></html>", None))
        self.img_ultimato.setText("")
        self.img_minions.setText("")
        self.img_tel_preto.setText("")
        self.img_fragmentado.setText("")
        self.img_invDoMal.setText("")
        self.txt_invDoMal.setText(QCoreApplication.translate("Home", u"<html><head/><body><p><span style=\" color:#ffffff; vertical-align:super;\">Invoca\u00e7\u00e3o do Mal (2013)</span></p></body></html>", None))
        self.txt_ultimato.setText(QCoreApplication.translate("Home", u"<html><head/><body><p><span style=\" vertical-align:super;\">Vingadores Ultimato (2019)</span></p></body></html>", None))
        self.txt_minios.setText(QCoreApplication.translate("Home", u"<html><head/><body><p><span style=\" vertical-align:super;\">Minions 4 (2024)</span></p></body></html>", None))
        self.txt_tel_preto.setText(QCoreApplication.translate("Home", u"<html><head/><body><p><span style=\" vertical-align:super;\">Telefone Preto (2021)</span></p></body></html>", None))
        self.txt_fragmentado.setText(QCoreApplication.translate("Home", u"<html><head/><body><p><span style=\" vertical-align:super;\">Fragmentado (2016)</span></p></body></html>", None))
    # retranslateUi
if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_Home()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())